#!/bin/sh

echo "Removing build files..."
echo

set -x

#rm -rv ./src/_vendor/pypinyin*/
rm -r ./src/_vendor/
rm -rv ./data/
rm -v ./src/data/custom_phrases_dict.py

{ set +x; } 2> /dev/null

echo
echo "Done."
